# Site Settings
theme: jekyll-theme-chirpy
lang: en
timezone: America/Vancouver

title: Jacob Macdonnell
tagline: Cybersecurity Portfolio and Projects
description: >-
  A cybersecurity portfolio featuring writeups, projects, and technical explorations by Jacob Macdonnell.

url: "https://jacobmacdonnell.github.io"

github:
  username: jacobmacdonnell

social:
  name: Jacob Macdonnell
  email: jacobmacdonnell1@gmail.com
  links:
    - https://github.com/jacobmacdonnell

webmaster_verifications:
  google:
  bing:
  alexa:
  yandex:
  baidu:
  facebook:

analytics:
  google:
    id: 
  goatcounter:
    id: 
  umami:
    id: 
    domain: 
  matomo:
    id: 
    domain: 
  cloudflare:
    id: 
  fathom:
    id: 

pageviews:
  provider:

theme_mode: 

cdn:

avatar:

social_preview_image: /assets/img/preview.png # <- You can replace with your image file under /assets/img/

toc: true

comments:
  provider:

assets:
  self_host:
    enabled:

pwa:
  enabled: false
  cache:
    enabled: false
    deny_paths:

paginate: 10

baseurl: ""

# Markdown Settings
kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    block:
      line_numbers: true
      start_line: 1

# Collections
collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: false
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - rollup.config.js
  - "package*.json"

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
